### ISSUE TITLE
failed when isc-dhcp-client is not installed

### ISSUE THREAD

**Issue by davidak** [kbrebanov/ansible-resolv_conf#2]
we have our Ubuntu servers installed via debootstrap and the minimal image, so we have only the packages we really need.

since the package [isc-dhcp-client](https://launchpad.net/ubuntu/trusty/+package/isc-dhcp-client) is not installed, i get this error with your ansible role:

```
fatal: [dev-ansible-trusty]: FAILED! => {"changed": false, "checksum": "ca23d7ed79204c422d0ea9c3b2b7752b13595697", "failed": true, "msg": "Destination directory /etc/dhcp/dhclient-enter-hooks.d does not exist"}
```

a solution would be to install it.

**Comment by kbrebanov** [comment]
This Ansible role is no longer being maintained.
